/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/brand-kits/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enqueue a brand-kit scrape from a URL
         * @description Enqueue a scrape. Body validation (URL + slug regex) happens in the schema.
         *
         *     SSRF protection is inherited from ``flyer_generator/brand_kit/scraper.py``
         *     which runs inside ``task_fetch_brand_kit``. This route DOES NOT bypass it —
         *     it only forwards ``url`` + ``slug``.
         */
        post: operations["create_brand_kit_fetch_api_v1_brand_kits_fetch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brand-kits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List brand kits (DB + filesystem fuse)
         * @description Return DB rows unioned with filesystem-only kits (lazy fuse — no INSERT).
         *
         *     RESEARCH.md Open Question Q3 recommendation: synthesize ``BrandKitSummary``
         *     entries in-memory for slugs present on disk but not yet in the DB. This is
         *     safe for v1 where at most a few dozen kits exist.  A real "import to DB"
         *     step is a later phase.
         */
        get: operations["list_brand_kits_api_v1_brand_kits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brand-kits/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Brand-kit detail (palette + typography + logos + voice)
         * @description Load a single brand kit.
         *
         *     Resolution order:
         *       1. DB row (fast path — preferred).
         *       2. Filesystem via ``load_brand_kit(slug, base_dir=...)``.
         *       3. Missing -> ``load_brand_kit`` raises ``BrandKitNotFoundError``
         *          which the exception-handler bank maps to HTTP 404.
         */
        get: operations["get_brand_kit_api_v1_brand_kits__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/flyers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enqueue a flyer generation
         * @description Enqueue a flyer generation.
         *
         *     Commit order is load-bearing:
         *       1. INSERT JobRecord, COMMIT.
         *       2. Then ``arq_pool.enqueue_job(...)`` — if we enqueued first, the worker
         *          could pick the job up before our row is visible and ``mark_running``
         *          would fail with a FK-style "no such job" error.
         */
        post: operations["create_flyer_api_v1_flyers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brochures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue a brochure generation (3 artifacts: front PNG + back PNG + PDF) */
        post: operations["create_brochure_api_v1_brochures_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue a single-platform social post generation */
        post: operations["create_social_post_api_v1_social_posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue a multi-platform social campaign (shared hero) */
        post: operations["create_social_campaign_api_v1_social_campaigns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll a job's status + result reference
         * @description Return the current status of a job plus a stable result reference.
         *
         *     - Single-artifact jobs (flyer, single post, brochure): ``result_ref`` is
         *       a string URL path like ``/api/v1/renders/<ulid>/image``.
         *     - Campaign jobs: ``result_ref`` is a list of :class:`ResultLink`
         *       (``platform``, ``url``) fused from ``CampaignRecord.posts`` +
         *       each ``PostRecord.render``.
         *     - Not-yet-succeeded jobs: ``result_ref`` is ``None``.
         */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/renders/{render_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream a render artifact (PNG / PDF / JPG)
         * @description Stream a render artifact to the client.
         *
         *     Returns 404 on ANY of the following (never distinguishing which):
         *
         *     - ``render_id`` not present in the ``renders`` table
         *     - ``file_path`` missing on disk
         *     - resolved ``file_path`` outside every configured artifact root (T-1)
         *     - ``file_path`` suffix not in the allowed extension whitelist
         */
        get: operations["get_render_image_api_v1_renders__render_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness check — does NOT touch the DB or Redis.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BackPanelContent
         * @description Structured back-cover content.
         *
         *     Unlike legacy BrochureBackPanel (which collapsed everything into a single
         *     string), this is a real object: heading + body + bullets + optional
         *     contact card + CTA button label.
         */
        BackPanelContent: {
            /**
             * Kind
             * @default cta
             */
            kind: string;
            /** Heading */
            heading?: string | null;
            /** Body */
            body?: string | null;
            /** Bullets */
            bullets?: string[];
            /** Cta Label */
            cta_label?: string | null;
            /** Cta Detail */
            cta_detail?: string | null;
            /** Footer Note */
            footer_note?: string | null;
        };
        /**
         * BrandKit
         * @description Top-level brand kit. Optional nested models allow partial scrapes.
         */
        BrandKit: {
            /** Name */
            name: string;
            /** Source Url */
            source_url?: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            palette?: components["schemas"]["BrandPalette"] | null;
            typography?: components["schemas"]["BrandTypography"] | null;
            /** Logos */
            logos?: components["schemas"]["BrandLogo"][];
            voice?: components["schemas"]["BrandVoice"] | null;
            photography?: components["schemas"]["BrandPhotoHints"] | null;
            /** Source Artifacts */
            source_artifacts?: string[];
            /**
             * Size Multiplier
             * @default 1
             */
            size_multiplier: number;
        };
        /**
         * BrandKitDetail
         * @description Response for GET /api/v1/brand-kits/{slug}.
         *
         *     Wraps the existing :class:`BrandKit` Pydantic model (which already has all
         *     palette / typography / logos / voice fields). Exposed as-is — no reshape.
         */
        BrandKitDetail: {
            /** Slug */
            slug: string;
            /**
             * Record Created At
             * Format: date-time
             */
            record_created_at: string;
            brand_kit: components["schemas"]["BrandKit"];
        };
        /**
         * BrandKitFetchRequest
         * @description Body of POST /api/v1/brand-kits/fetch.
         */
        BrandKitFetchRequest: {
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Slug */
            slug: string;
        };
        /**
         * BrandKitSummary
         * @description Entry in GET /api/v1/brand-kits list.
         */
        BrandKitSummary: {
            /** Slug */
            slug: string;
            /** Name */
            name?: string | null;
            /** Source Url */
            source_url?: string | null;
            /**
             * Scraped At
             * Format: date-time
             */
            scraped_at: string;
        };
        /**
         * BrandLogo
         * @description A single logo asset (stored at kit_dir / path).
         */
        BrandLogo: {
            /** Path */
            path: string;
            /**
             * Variant
             * @enum {string}
             */
            variant: "primary" | "mono_dark" | "mono_light" | "mark_only";
            /**
             * Format
             * @enum {string}
             */
            format: "png" | "jpg" | "svg";
            /** Aspect Ratio */
            aspect_ratio: number;
        };
        /**
         * BrandPalette
         * @description Extracted brand color palette: five named roles + an extras dict.
         */
        BrandPalette: {
            primary: components["schemas"]["ColorUsage"];
            secondary: components["schemas"]["ColorUsage"];
            accent: components["schemas"]["ColorUsage"];
            neutral_dark: components["schemas"]["ColorUsage"];
            neutral_light: components["schemas"]["ColorUsage"];
            /** Extras */
            extras?: {
                [key: string]: components["schemas"]["ColorUsage"];
            };
        };
        /**
         * BrandPhotoHints
         * @description Optional photography guidance.
         */
        BrandPhotoHints: {
            /** Preferred Style Preset */
            preferred_style_preset?: string | null;
            /** Color Grade Notes */
            color_grade_notes?: string | null;
        };
        /**
         * BrandTypography
         * @description Heading + body font stacks and a generic size scale.
         *
         *     `size_scale` keys are role tokens (`hero`, `display`, `heading`,
         *     `subheading`, `body`, `caption`). The applier maps these to the
         *     template's specific size fields.
         */
        BrandTypography: {
            /** Heading Family */
            heading_family: string;
            /** Body Family */
            body_family: string;
            /** Size Scale */
            size_scale?: {
                [key: string]: number;
            };
            /** Font Sources */
            font_sources?: string[];
        };
        /**
         * BrandVoice
         * @description Optional brand voice hints (captured now, wired to text_gen later).
         */
        BrandVoice: {
            /** Tone */
            tone: string;
            /** Example Phrases */
            example_phrases?: string[];
            /** Banned Words */
            banned_words?: string[];
        };
        /**
         * BrochureBrief
         * @description Customer intake for brochure content.
         *
         *     This is the interrogative data you'd collect from a customer before
         *     writing a brochure: what they do, who they serve, what sets them apart,
         *     what evidence they can show, what action they want the reader to take,
         *     what voice they speak in. The LLM consumes this as ground truth when
         *     writing copy — anything in here should appear verbatim or nearly so in
         *     the final brochure (instead of being invented by the model).
         *
         *     Intended inputs:
         *       * Hand-filled by the caller (CLI or API).
         *       * Auto-populated by a future website scraper (firecrawl) — fields map
         *         cleanly onto what you'd extract from a landing page + about + services.
         */
        BrochureBrief: {
            /** Target Audience */
            target_audience?: string | null;
            /** Brand Voice */
            brand_voice?: string | null;
            /** Value Proposition */
            value_proposition?: string | null;
            /** Offerings */
            offerings?: string[];
            /** Differentiators */
            differentiators?: string[];
            /** Testimonials */
            testimonials?: components["schemas"]["Testimonial"][];
            /** Awards */
            awards?: string[];
            /** Key Stats */
            key_stats?: string[];
            /** Founded Year */
            founded_year?: number | null;
            /** Hours */
            hours?: string | null;
            /** Locations */
            locations?: string[];
            /** Primary Cta */
            primary_cta?: string | null;
            /** Secondary Cta */
            secondary_cta?: string | null;
            /** Keywords */
            keywords?: string[];
            /** Source Urls */
            source_urls?: string[];
        };
        /**
         * BrochureContent
         * @description Primary content model for the schema renderer.
         */
        BrochureContent: {
            /** Title */
            title: string;
            /** Subtitle */
            subtitle?: string | null;
            /** Tagline */
            tagline?: string | null;
            /** Org */
            org: string;
            /** Hero Concept */
            hero_concept?: string | null;
            /**
             * Color Accent
             * @default #1E3A5F
             */
            color_accent: string;
            contact?: components["schemas"]["ContactBlock"] | null;
            /** Sections */
            sections: components["schemas"]["ContentSection"][];
            back_panel?: components["schemas"]["BackPanelContent"] | null;
            brief?: components["schemas"]["BrochureBrief"] | null;
            /** Extras */
            extras?: {
                [key: string]: string;
            };
        };
        /**
         * BrochureCreateRequest
         * @description Body of POST /api/v1/brochures.
         */
        BrochureCreateRequest: {
            content: components["schemas"]["BrochureContent"];
            /** Template */
            template: string;
            /** Brand Kit Slug */
            brand_kit_slug?: string | null;
            /**
             * Generate Images
             * @default true
             */
            generate_images: boolean;
            /**
             * Workflow
             * @default turbo_landscape
             */
            workflow: string;
            /**
             * Style Preset
             * @default photorealistic
             */
            style_preset: string;
        };
        /**
         * CampaignCreateRequest
         * @description Body of POST /api/v1/social/campaigns.
         */
        CampaignCreateRequest: {
            /** Brand Kit Slug */
            brand_kit_slug: string;
            /** Platforms */
            platforms: ("linkedin" | "twitter" | "instagram" | "facebook")[];
            /**
             * Intent
             * @enum {string}
             */
            intent: "announcement" | "value-prop" | "testimonial";
            /** Topic */
            topic: string;
            /** Cta */
            cta?: string | null;
            /** Style Preset */
            style_preset?: string | null;
        };
        /**
         * ColorUsage
         * @description A single color with an optional semantic usage hint.
         */
        ColorUsage: {
            /** Hex */
            hex: string;
            /** Usage Hint */
            usage_hint?: string | null;
        };
        /**
         * ContactBlock
         * @description Optional contact block used on the back cover panel.
         */
        ContactBlock: {
            /** Name */
            name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** Url */
            url?: string | null;
            /** Address */
            address?: string | null;
        };
        /**
         * ContentSection
         * @description One content section mapped onto tuck_flap or inner_{left,center,right}.
         */
        ContentSection: {
            /** Heading */
            heading: string;
            /** Lead Paragraph */
            lead_paragraph?: string | null;
            /** Body Paragraphs */
            body_paragraphs?: string[];
            /** Bullets */
            bullets?: string[];
            /** Quote */
            quote?: string | null;
            /** Quote Attribution */
            quote_attribution?: string | null;
            /** Icon Hint */
            icon_hint?: string | null;
            /** Image Concept */
            image_concept?: string | null;
        };
        /**
         * EventInput
         * @description Structured event data — the pipeline's primary input.
         */
        EventInput: {
            /** Title */
            title: string;
            /** Date */
            date: string;
            /** Time */
            time: string;
            /** Location Name */
            location_name: string;
            /** Location Address */
            location_address: string;
            /** Fees */
            fees: string;
            /** Org */
            org: string;
            /** Url */
            url?: string | null;
            /** Style Concept */
            style_concept: string;
            /** Style Preset */
            style_preset: string;
            /**
             * Color Accent
             * @default #F59E0B
             */
            color_accent: string;
        };
        /**
         * FlyerCreateRequest
         * @description Body of POST /api/v1/flyers.
         *
         *     Re-uses EventInput verbatim (no field-by-field redefinition). Adds API-layer
         *     options: optional brand-kit slug, optional accent override, optional max
         *     background retry cap.
         */
        FlyerCreateRequest: {
            event: components["schemas"]["EventInput"];
            /** Preset */
            preset: string;
            /** Brand Kit Slug */
            brand_kit_slug?: string | null;
            /** Accent */
            accent?: string | null;
            /** Max Bg Attempts */
            max_bg_attempts?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobCreated
         * @description Response body for every async-job-starting endpoint (202 Accepted).
         */
        JobCreated: {
            /**
             * Job Id
             * @description ULID job id
             */
            job_id: string;
        };
        /**
         * JobDetail
         * @description GET /api/v1/jobs/{id} response.
         */
        JobDetail: {
            /** Id */
            id: string;
            kind: components["schemas"]["JobKind"];
            status: components["schemas"]["JobStatus"];
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Error Detail */
            error_detail?: {
                [key: string]: unknown;
            } | null;
            /** Result Ref */
            result_ref?: string | components["schemas"]["ResultLink"][] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * JobKind
         * @enum {string}
         */
        JobKind: "brand_kit" | "flyer" | "brochure" | "social_post" | "social_campaign";
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /**
         * PaginatedBrandKits
         * @description Response for GET /api/v1/brand-kits?limit=&offset=.
         */
        PaginatedBrandKits: {
            /** Items */
            items: components["schemas"]["BrandKitSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * PostCreateRequest
         * @description Body of POST /api/v1/social/posts.
         *
         *     Mirrors PostBrief fields but ADDS brand_kit_slug + style_preset at the
         *     API boundary so the task can resolve the kit + pick a Comfy workflow.
         */
        PostCreateRequest: {
            /** Brand Kit Slug */
            brand_kit_slug: string;
            /**
             * Platform
             * @enum {string}
             */
            platform: "linkedin" | "twitter" | "instagram" | "facebook";
            /**
             * Intent
             * @enum {string}
             */
            intent: "announcement" | "value-prop" | "testimonial";
            /** Topic */
            topic: string;
            /** Cta */
            cta?: string | null;
            /** Image Hint */
            image_hint?: string | null;
            /** Style Preset */
            style_preset?: string | null;
        };
        /**
         * ResultLink
         * @description One entry in a campaign's `result_ref` list.
         */
        ResultLink: {
            /** Platform */
            platform: string;
            /** Url */
            url: string;
        };
        /**
         * Testimonial
         * @description A single customer quote.
         */
        Testimonial: {
            /** Quote */
            quote: string;
            /** Attribution */
            attribution?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_brand_kit_fetch_api_v1_brand_kits_fetch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandKitFetchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_brand_kits_api_v1_brand_kits_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBrandKits"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_brand_kit_api_v1_brand_kits__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandKitDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_flyer_api_v1_flyers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlyerCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_brochure_api_v1_brochures_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrochureCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_social_post_api_v1_social_posts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_social_campaign_api_v1_social_campaigns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_render_image_api_v1_renders__render_id__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                render_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
