"""initial schema

Revision ID: 2f5971e114b3
Revises: 
Create Date: 2026-04-22 17:25:04.623657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f5971e114b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_kits',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('kind', sa.Enum('BRAND_KIT', 'FLYER', 'BROCHURE', 'SOCIAL_POST', 'SOCIAL_CAMPAIGN', name='jobkind'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_detail', sa.JSON(), nullable=True),
    sa.Column('result_ref', sa.String(length=26), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_result_ref'), ['result_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_trace_id'), ['trace_id'], unique=False)

    op.create_table('renders',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('comfy_job_id', sa.String(length=64), nullable=True),
    sa.Column('vision_verdict', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('renders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_renders_kind'), ['kind'], unique=False)

    op.create_table('brochures',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('template', sa.String(length=64), nullable=False),
    sa.Column('brand_kit_slug', sa.String(length=64), nullable=True),
    sa.Column('content_payload', sa.JSON(), nullable=False),
    sa.Column('render_front_id', sa.String(length=26), nullable=True),
    sa.Column('render_back_id', sa.String(length=26), nullable=True),
    sa.Column('render_pdf_id', sa.String(length=26), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_kit_slug'], ['brand_kits.slug'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['render_back_id'], ['renders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['render_front_id'], ['renders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['render_pdf_id'], ['renders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brochures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brochures_brand_kit_slug'), ['brand_kit_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_brochures_render_back_id'), ['render_back_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brochures_render_front_id'), ['render_front_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brochures_render_pdf_id'), ['render_pdf_id'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('topic', sa.String(length=400), nullable=False),
    sa.Column('intent', sa.String(length=40), nullable=False),
    sa.Column('brand_kit_slug', sa.String(length=64), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('summary_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_kit_slug'], ['brand_kits.slug'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_brand_kit_slug'), ['brand_kit_slug'], unique=False)

    op.create_table('flyers',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('preset', sa.String(length=64), nullable=False),
    sa.Column('brand_kit_slug', sa.String(length=64), nullable=True),
    sa.Column('event_payload', sa.JSON(), nullable=False),
    sa.Column('render_id', sa.String(length=26), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_kit_slug'], ['brand_kits.slug'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['render_id'], ['renders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flyers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flyers_brand_kit_slug'), ['brand_kit_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_flyers_render_id'), ['render_id'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('intent', sa.String(length=40), nullable=False),
    sa.Column('topic', sa.String(length=400), nullable=False),
    sa.Column('brand_kit_slug', sa.String(length=64), nullable=True),
    sa.Column('campaign_id', sa.String(length=26), nullable=True),
    sa.Column('post_payload', sa.JSON(), nullable=False),
    sa.Column('render_id', sa.String(length=26), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_kit_slug'], ['brand_kits.slug'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['render_id'], ['renders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_brand_kit_slug'), ['brand_kit_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_render_id'), ['render_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_render_id'))
        batch_op.drop_index(batch_op.f('ix_posts_platform'))
        batch_op.drop_index(batch_op.f('ix_posts_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_posts_brand_kit_slug'))

    op.drop_table('posts')
    with op.batch_alter_table('flyers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flyers_render_id'))
        batch_op.drop_index(batch_op.f('ix_flyers_brand_kit_slug'))

    op.drop_table('flyers')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_brand_kit_slug'))

    op.drop_table('campaigns')
    with op.batch_alter_table('brochures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brochures_render_pdf_id'))
        batch_op.drop_index(batch_op.f('ix_brochures_render_front_id'))
        batch_op.drop_index(batch_op.f('ix_brochures_render_back_id'))
        batch_op.drop_index(batch_op.f('ix_brochures_brand_kit_slug'))

    op.drop_table('brochures')
    with op.batch_alter_table('renders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_renders_kind'))

    op.drop_table('renders')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_trace_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_result_ref'))
        batch_op.drop_index(batch_op.f('ix_jobs_kind'))

    op.drop_table('jobs')
    op.drop_table('brand_kits')
    # ### end Alembic commands ###
