"""Text measurement + wrap + budget math.

No browser / canvas dependency. We use a character-width lookup table
(roughly calibrated to Inter / Source Serif Pro / Playfair at their
nominal weights) to estimate widths in "em units" then scale by font_size.
This is accurate to within ±8% for Latin text, which is plenty for
fit-to-bbox decisions — we deliberately leave a 10% safety margin.
"""

from __future__ import annotations

from dataclasses import dataclass


# Em-unit widths for ASCII characters, averaged across common UI fonts.
# Generated by eyeballing a few commercial font metrics tables; good enough
# for wrap decisions. Unknown glyphs fall back to 0.55 em.
_CHAR_WIDTH_EM: dict[str, float] = {
    " ": 0.25, "!": 0.28, '"': 0.39, "#": 0.55, "$": 0.55, "%": 0.88,
    "&": 0.67, "'": 0.22, "(": 0.33, ")": 0.33, "*": 0.47, "+": 0.58,
    ",": 0.28, "-": 0.33, ".": 0.28, "/": 0.28,
    "0": 0.55, "1": 0.55, "2": 0.55, "3": 0.55, "4": 0.55,
    "5": 0.55, "6": 0.55, "7": 0.55, "8": 0.55, "9": 0.55,
    ":": 0.28, ";": 0.28, "<": 0.58, "=": 0.58, ">": 0.58,
    "?": 0.55, "@": 1.01,
    "A": 0.67, "B": 0.67, "C": 0.72, "D": 0.72, "E": 0.67,
    "F": 0.61, "G": 0.78, "H": 0.72, "I": 0.28, "J": 0.50,
    "K": 0.67, "L": 0.56, "M": 0.83, "N": 0.72, "O": 0.78,
    "P": 0.67, "Q": 0.78, "R": 0.72, "S": 0.67, "T": 0.61,
    "U": 0.72, "V": 0.67, "W": 0.94, "X": 0.67, "Y": 0.67, "Z": 0.61,
    "[": 0.28, "\\": 0.28, "]": 0.28, "^": 0.47, "_": 0.55, "`": 0.33,
    "a": 0.55, "b": 0.55, "c": 0.50, "d": 0.55, "e": 0.55,
    "f": 0.28, "g": 0.55, "h": 0.55, "i": 0.22, "j": 0.22,
    "k": 0.50, "l": 0.22, "m": 0.83, "n": 0.55, "o": 0.55,
    "p": 0.55, "q": 0.55, "r": 0.33, "s": 0.50, "t": 0.28,
    "u": 0.55, "v": 0.50, "w": 0.72, "x": 0.50, "y": 0.50, "z": 0.50,
    "{": 0.33, "|": 0.25, "}": 0.33, "~": 0.58,
}

_DEFAULT_EM = 0.55


def _serif_scale(font_family: str) -> float:
    """Rough calibration bump for serif bodies."""
    if not font_family:
        return 1.0
    lower = font_family.lower()
    if "playfair" in lower or "source serif" in lower or "georgia" in lower or "times" in lower or "serif" in lower:
        return 1.05
    if "fredoka" in lower:
        return 1.02
    return 1.0


def measure_text(text: str, font_size: int, font_family: str = "") -> tuple[float, float]:
    """Return (width_px, height_px) estimate for a single line of text."""
    em = sum(_CHAR_WIDTH_EM.get(ch, _DEFAULT_EM) for ch in text)
    width = em * font_size * _serif_scale(font_family)
    return (width, float(font_size))


def chars_per_line(
    bbox_width: float, font_size: int, font_family: str = "", safety: float = 0.92
) -> int:
    """How many 'average' characters fit on one line at this font size in this width.

    `safety` under 1.0 provides a margin so we don't cut things too close.
    """
    avg_em = 0.50  # slightly narrower than the mean since we mostly render body text
    px_per_char = avg_em * font_size * _serif_scale(font_family)
    usable = bbox_width * safety
    return max(1, int(usable / px_per_char))


def wrap_text(text: str, max_chars_per_line: int) -> list[str]:
    """Greedy word wrap. Falls back to hard-breaking words longer than the limit."""
    if not text:
        return []
    lines: list[str] = []
    for paragraph in text.split("\n"):
        words = paragraph.strip().split()
        current = ""
        for word in words:
            candidate = word if not current else f"{current} {word}"
            if len(candidate) <= max_chars_per_line:
                current = candidate
            else:
                if current:
                    lines.append(current)
                if len(word) > max_chars_per_line:
                    # Hard-break
                    for i in range(0, len(word), max_chars_per_line):
                        lines.append(word[i : i + max_chars_per_line])
                    current = ""
                else:
                    current = word
        if current:
            lines.append(current)
        lines.append("")  # paragraph break
    # Trim trailing blank
    while lines and lines[-1] == "":
        lines.pop()
    return lines


@dataclass(frozen=True)
class FittedText:
    lines: list[str]
    total_height: float
    overflowed: bool  # True when content had to be truncated to fit


def fit_to_bbox(
    text: str,
    bbox: tuple[float, float, float, float],
    font_size: int,
    line_height: int,
    font_family: str = "",
    max_chars_per_line: int | None = None,
) -> FittedText:
    """Wrap `text` into lines that fit bbox width; truncate at bbox height."""
    _, _, w, h = bbox
    if max_chars_per_line is None:
        max_chars_per_line = chars_per_line(w, font_size, font_family)
    all_lines = wrap_text(text, max_chars_per_line)
    # paragraph breaks show up as empty strings; preserve them as half-line gaps
    max_lines = int(h / line_height)
    if max_lines <= 0:
        return FittedText(lines=[], total_height=0.0, overflowed=True)
    overflowed = False
    if len(all_lines) > max_lines:
        all_lines = all_lines[:max_lines]
        overflowed = True
    total = len(all_lines) * line_height
    return FittedText(lines=all_lines, total_height=total, overflowed=overflowed)


def char_budget_for_bbox(
    bbox: tuple[float, float, float, float],
    font_size: int,
    line_height: int,
    font_family: str = "",
) -> int:
    """Max characters a bbox can hold at the given font settings.

    Used by Phase 2 to tell the LLM how many characters to write for a region.
    chars_per_line already underestimates by ~8% so we're never at the literal
    edge.

    Line count uses `round(h / line_height)` rather than `int(...)` so a bbox
    that fits 1.5+ lines reports 2-line capacity. Floor-int was too aggressive:
    a 190px-tall title bbox with 108px line_height actually holds 1-2 lines in
    practice (the renderer wraps both), but `int(1.76) == 1` reported half the
    real capacity, forcing the LLM to write nonsensically short titles.
    """
    _, _, w, h = bbox
    cpl = chars_per_line(w, font_size, font_family)
    max_lines = max(1, round(h / line_height))
    return cpl * max_lines
